/**
 * localCache.ts
 *
 * Reads JSON files generated by the ListSyncer console app from
 * /lists/{type}/{slug}.json (served as static assets by Vite / GitHub Pages).
 *
 * Format written by ListSyncer:
 *   { syncedAt, slug, type, totalItems, data: T }
 *
 * If the file is not found (404) or any fetch error occurs, every
 * function returns null so the caller falls back to the live API.
 */

import type { SourceGameListDto, GameListCollectionResponse } from './gameLists'
import type { GameListCategoryDto, HomeList, Pager } from '../types'

interface CacheEnvelope<T> {
  syncedAt: string
  slug: string
  type: number   // CacheType enum: 0=Final, 1=Critic, 2=User
  totalItems: number
  data: T
}

// ── Internal helpers ──────────────────────────────────────────────────────────

async function tryReadCache<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path)
    if (!res.ok) return null
    return (await res.json()) as T
  } catch {
    return null
  }
}

function buildCollectionResponse(
  allLists: SourceGameListDto[],
  page: number,
  pageSize: number,
): GameListCollectionResponse {
  const totalItems = allLists.length
  const totalPages = Math.max(1, Math.ceil(totalItems / pageSize))
  const safePage = Math.min(Math.max(1, page), totalPages)
  const start = (safePage - 1) * pageSize

  return {
    lists: allLists.slice(start, start + pageSize),
    pager: {
      currentPage: safePage,
      pageSize,
      totalItems,
      totalPages,
      maxPages: 5,
    },
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function getCriticListsFromCache(
  slug: string,
  page: number,
  pageSize: number,
): Promise<GameListCollectionResponse | null> {
  const envelope = await tryReadCache<CacheEnvelope<SourceGameListDto[]>>(
    `/lists/critic/${slug}.json`,
  )
  if (!envelope?.data) return null
  return buildCollectionResponse(envelope.data, page, pageSize)
}

export async function getUserListsFromCache(
  slug: string,
  page: number,
  pageSize: number,
): Promise<GameListCollectionResponse | null> {
  const envelope = await tryReadCache<CacheEnvelope<SourceGameListDto[]>>(
    `/lists/user/${slug}.json`,
  )
  if (!envelope?.data) return null
  return buildCollectionResponse(envelope.data, page, pageSize)
}

// ── Lists index (for /lists page) ────────────────────────────────────────────

interface ListsIndex {
  syncedAt: string
  data: GameListCategoryDto[]
}

let _indexCache: GameListCategoryDto[] | null = null

async function getIndex(): Promise<GameListCategoryDto[] | null> {
  if (_indexCache) return _indexCache
  const index = await tryReadCache<ListsIndex>('/lists/index.json')
  if (!index?.data) {
    console.warn('[localCache] index.json not found — falling back to API')
    return null
  }
  _indexCache = index.data
  console.info(`[localCache] index.json loaded (${_indexCache.length} lists, synced ${index.syncedAt})`)
  return _indexCache
}

// Derive tags from slug when the backend hasn't been deployed with tagList yet.
// Mirrors the same keyword logic from Tags.cs / FilterListsCategory on the backend.
const TAG_KEYWORDS: Record<string, string[]> = {
  'all time':    ['all-time'],
  'year':        [], // matched by year field below
  'mobile':      ['mobile'],
  'console':     ['playstation', 'xbox', 'nintendo', 'sega', 'atari', 'wii', 'switch',
                  'gamecube', 'dreamcast', 'nes', 'snes', 'mega-drive', 'master-system'],
  'nintendo':    ['nintendo', 'nes', 'snes', 'gamecube', 'wii', 'switch', 'game-boy',
                  'ds', '3ds', 'game-boy-advance', 'game-boy-color'],
  'playstation': ['playstation', 'psvr', 'ps-vita'],
  'xbox':        ['xbox'],
  'sega':        ['mega-drive', 'dreamcast', 'master-system'],
  'atari':       ['atari'],
  'handheld':    ['game-boy', 'ds', '3ds', 'psp', 'ps-vita', 'game-boy-advance',
                  'game-boy-color'],
  'vr':          ['vr', 'psvr', 'oculus', 'meta-quest'],
  'pc':          ['pc', 'steam'],
  'valve':       ['steam-deck', 'steam'],
  'genre':       ['rpg', 'fighting', 'strategy', 'open-world', 'walking-simulator',
                  'survival-horror', 'action-adventure', 'mmorpg', 'indie'],
}

function inferTagList(c: GameListCategoryDto): string[] {
  // If the backend already provided tagList, use it
  if (c.tagList?.length) return c.tagList

  const s = c.slug.toLowerCase()
  const tags: string[] = ['all']

  if (c.year != null) tags.push('year')

  for (const [tag, keywords] of Object.entries(TAG_KEYWORDS)) {
    if (keywords.some(kw => s.includes(kw))) {
      tags.push(tag)
    }
  }

  return tags
}

function categoryToHomeList(c: GameListCategoryDto): HomeList {
  return {
    id: c.id,
    title: c.title,
    year: c.year,
    numberOfGames: c.numberOfGames,
    numberOfSources: c.numberOfSources,
    slug: c.slug,
    topThreeWinners: c.topWinners.slice(0, 3).map(w => ({
      gameId: w.gameId,
      gameTitle: w.gameTitle,
      coverImageUrl: w.coverImageUrl,
    })),
  }
}

export interface GetListsResult {
  lists: HomeList[]
  pager: Pager
}

export async function getListsFromCache(params: {
  page: number
  pageSize: number
  tags: string[]
  search: string
}): Promise<GetListsResult | null> {
  const all = await getIndex()
  if (!all) return null

  const { page, pageSize, tags, search } = params
  const filterAll = tags.length === 0 || tags.includes('all')

  let filtered = all

  if (!filterAll) {
    filtered = filtered.filter(c =>
      tags.some(tag => inferTagList(c).includes(tag.toLowerCase()))
    )
  }

  if (search.trim()) {
    const q = search.trim().toLowerCase()
    filtered = filtered.filter(c =>
      c.title.toLowerCase().includes(q) || String(c.year ?? '').includes(q)
    )
  }

  const totalItems = filtered.length
  const totalPages = Math.max(1, Math.ceil(totalItems / pageSize))
  const safePage = Math.min(Math.max(1, page), totalPages)
  const start = (safePage - 1) * pageSize

  return {
    lists: filtered.slice(start, start + pageSize).map(categoryToHomeList),
    pager: { currentPage: safePage, pageSize, totalItems, totalPages, maxPages: 5 },
  }
}

// Tags are static — hardcode to avoid an extra API call when index is available
const STATIC_TAGS = ['all', 'all time', 'mobile', 'console', 'nintendo', 'playstation',
  'xbox', 'year', 'sega', 'atari', 'handheld', 'vr', 'pc', 'valve', 'genre']

export async function getTagsFromCache(): Promise<string[] | null> {
  const all = await getIndex()
  if (!all) return null
  return STATIC_TAGS
}

// ── Final list detail (for /list/{slug} page) ────────────────────────────────

import type { GameListDetailsResponse } from './gameLists'

export async function getListBySlugFromCache(
  slug: string,
): Promise<GameListDetailsResponse | null> {
  const envelope = await tryReadCache<CacheEnvelope<GameListDetailsResponse>>(
    `/lists/final/${slug}.json`,
  )
  return envelope?.data ?? null
}

// ── API warm-up ───────────────────────────────────────────────────────────────
// When the lists page loads from cache the Render backend stays cold.
// Fire a cheap background ping so it's warm by the time the user clicks a list.

let _warmedUp = false

export function warmUpApi(baseUrl: string): void {
  if (_warmedUp) return
  _warmedUp = true
  fetch(`${baseUrl}/api/game-lists/categories?page=1&pageSize=1`)
    .catch(() => { /* silent — this is best-effort */ })
}
