/**
 * localCache.ts
 *
 * Reads JSON files generated by the ListSyncer console app from
 * /lists/{type}/{slug}.json (served as static assets by Vite / GitHub Pages).
 *
 * Format written by ListSyncer:
 *   { syncedAt, slug, type, totalItems, data: T }
 *
 * If the file is not found (404) or any fetch error occurs, every
 * function returns null so the caller falls back to the live API.
 */

import type { SourceGameListDto, GameListCollectionResponse } from './gameLists'
import type { GameListCategoryDto, HomeList, Pager } from '../types'

interface CacheEnvelope<T> {
  syncedAt: string
  slug: string
  type: number   // CacheType enum: 0=Final, 1=Critic, 2=User
  totalItems: number
  data: T
}

// ── Internal helpers ──────────────────────────────────────────────────────────

async function tryReadCache<T>(path: string): Promise<T | null> {
  try {
    const res = await fetch(path)
    if (!res.ok) return null
    return (await res.json()) as T
  } catch {
    return null
  }
}

function buildCollectionResponse(
  allLists: SourceGameListDto[],
  page: number,
  pageSize: number,
): GameListCollectionResponse {
  const totalItems = allLists.length
  const totalPages = Math.max(1, Math.ceil(totalItems / pageSize))
  const safePage = Math.min(Math.max(1, page), totalPages)
  const start = (safePage - 1) * pageSize

  return {
    lists: allLists.slice(start, start + pageSize),
    pager: {
      currentPage: safePage,
      pageSize,
      totalItems,
      totalPages,
      maxPages: 5,
    },
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export async function getCriticListsFromCache(
  slug: string,
  page: number,
  pageSize: number,
): Promise<GameListCollectionResponse | null> {
  const envelope = await tryReadCache<CacheEnvelope<SourceGameListDto[]>>(
    `/lists/critic/${slug}.json`,
  )
  if (!envelope?.data) return null
  return buildCollectionResponse(envelope.data, page, pageSize)
}

export async function getUserListsFromCache(
  slug: string,
  page: number,
  pageSize: number,
): Promise<GameListCollectionResponse | null> {
  const envelope = await tryReadCache<CacheEnvelope<SourceGameListDto[]>>(
    `/lists/user/${slug}.json`,
  )
  if (!envelope?.data) return null
  return buildCollectionResponse(envelope.data, page, pageSize)
}

// ── Lists index (for /lists page) ────────────────────────────────────────────

interface ListsIndex {
  syncedAt: string
  data: GameListCategoryDto[]
}

let _indexCache: GameListCategoryDto[] | null = null

async function getIndex(): Promise<GameListCategoryDto[] | null> {
  if (_indexCache) return _indexCache
  const index = await tryReadCache<ListsIndex>('/lists/index.json')
  if (!index?.data) return null
  _indexCache = index.data
  return _indexCache
}

function categoryToHomeList(c: GameListCategoryDto): HomeList {
  return {
    id: c.id,
    title: c.title,
    year: c.year,
    numberOfGames: c.numberOfGames,
    numberOfSources: c.numberOfSources,
    slug: c.slug,
    topThreeWinners: c.topWinners.slice(0, 3).map(w => ({
      gameId: w.gameId,
      gameTitle: w.gameTitle,
      coverImageUrl: w.coverImageUrl,
    })),
  }
}

export interface GetListsResult {
  lists: HomeList[]
  pager: Pager
}

export async function getListsFromCache(params: {
  page: number
  pageSize: number
  tags: string[]
  search: string
}): Promise<GetListsResult | null> {
  const all = await getIndex()
  if (!all) return null

  const { page, pageSize, tags, search } = params
  const filterAll = tags.length === 0 || tags.includes('all')

  let filtered = all

  if (!filterAll) {
    // If the index was generated by an older backend version, tagList may be null.
    // In that case, fall back to the live API so filtering still works correctly.
    if (!all[0]?.tagList?.length) return null

    filtered = filtered.filter(c =>
      tags.some(tag => (c.tagList ?? []).map(t => t.toLowerCase()).includes(tag.toLowerCase()))
    )
  }

  if (search.trim()) {
    const q = search.trim().toLowerCase()
    filtered = filtered.filter(c =>
      c.title.toLowerCase().includes(q) || String(c.year ?? '').includes(q)
    )
  }

  const totalItems = filtered.length
  const totalPages = Math.max(1, Math.ceil(totalItems / pageSize))
  const safePage = Math.min(Math.max(1, page), totalPages)
  const start = (safePage - 1) * pageSize

  return {
    lists: filtered.slice(start, start + pageSize).map(categoryToHomeList),
    pager: { currentPage: safePage, pageSize, totalItems, totalPages, maxPages: 5 },
  }
}

// Tags are static — hardcode to avoid an extra API call when index is available
const STATIC_TAGS = ['all', 'all time', 'mobile', 'console', 'nintendo', 'playstation',
  'xbox', 'year', 'sega', 'atari', 'handheld', 'vr', 'pc', 'valve', 'genre']

export async function getTagsFromCache(): Promise<string[] | null> {
  const all = await getIndex()
  if (!all) return null
  return STATIC_TAGS
}
